### ISSUE TITLE
Fatal error on running example code on Linux

### ISSUE THREAD

**Issue by chrishanretty** [malcolmbarrett/ggdag#11]
When I try to execute the code contained in the examples, I get a fatal error.

The code I use is:

```
library(ggdag)

tidy_ggdag <- dagify(y ~ x + z2 + w2 + w1,
             x ~ z1 + w1 + w2,
             z1 ~ w1 + v,
             z2 ~ w2 + v,
             w1 ~~ w2, # bidirected path
             exposure = "x",
             outcome = "y") %>% tidy_dagitty()
```

The message I get is:

```
Process R trace/breakpoint trap (core dumped) at Sat Jul  6 15:22:01 2019


#
# Fatal error in ../src/platform-linux.cc, line 782
# CHECK_EQ(0, result) failed
#   Expected: 0
#   Found: 22
#


==== Stack trace is not available ==========================


==== Isolate for the thread is not initialized =============
```

My system information is as follows:

platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo

**Comment by malcolmbarrett** [comment]
Based on your conversation in jtextor/dagitty#23, it doesn't look like this is a ggdag issue, so I'm going to close this. If it turns out to be, feel free to re-open
