### ISSUE TITLE
Manual layout?

### ISSUE THREAD

**Issue by johnfrombluff** [malcolmbarrett/ggdag#12]
Firstly, *thanks* for this great package. I'm not sure if this is best asked here or on the daggity github, but is it possible to easily create a manual layout? When you `tidy_dagitty(graph)`, the data frame has `x` and `y` variables. But when I modify them before passing to ggplot, it seems to have no effect. Also, when I pass my desired coordinates direct to ggplot, again it seems to have no effect. Does `geom_{node, edge, text}` modify the layout?

Here the function in which I'm trying to make this happen:
```r
layout <- tibble(x = c(1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1), 
                 y = c(2, 2, 2, 4, 2, 5, 2, 6, 1, 1, 1))

highlight_nodes <- function(g, ns = NULL, layout = NULL) {
  library(dplyr)
  d <- tidy_dagitty(g) 
  if ( is.null(ns) ) {
    p <- ggplot(d, aes(x = x, y = y, xend = xend, yend = yend))
  } else {
    d$x <- layout$x
    d$y <- layout$y
    d <- d %>% mutate(Z = ifelse(name %in% ns, TRUE, FALSE), edge_colour = ifelse(Z, "blue", "red"))
    p <- ggplot(d, aes(x = layout$x, y = layout$y, xend = xend, yend = yend, color = Z, group = Z))
  }
    
  p <- p +
    geom_dag_node() +
    geom_dag_edges() +
    geom_dag_text(col = "white") + 
    theme_dag() +
    theme(legend.position = "none")
  p <- p + scale_dag(breaks = c("X")) 
  return(invisible(p))  
}
```

**Comment by malcolmbarrett** [comment]
You can indeed use layouts like in your function; the only reason it's not having an effect is that you're saving the new layout to the wrong place. A `tidy_dagitty` object is a list of two other objects: the `data` tibble and the `dag` daggity object. So swap out e.g. `d$y` for `d$data$y`. You could also use the dplyr functions, which have methods to work directly with `data` without worrying about the internal structure.

That all said, I think the easiest way to set a manual layout is to use dagitty's approach. You can assign coordinates to a dagitty object with `dagitty::coordinates()` or pass it to the ggdag wrapper `dagify()` as a dataframe in the `coords` option. See the [ggdag docs for coordinates](https://ggdag.malco.io/reference/coordinates.html) and an [example from the vignettes](https://ggdag.malco.io/articles/bias-structures.html#measurement-error)

**Comment by johnfrombluff** [comment]
Awesome! Thank you *so* much for your quick and very helpful reply.
