### ISSUE TITLE
Draw lavaan models

### ISSUE THREAD

**Issue by nfultz** [malcolmbarrett/ggdag#16]
I am using [lavaan] for some SEM, would it be possible to use this package to make ggplot2-compatible diagrams, so that I could `+` on other geoms and easily map node colors back to a factor? 

[semPlot] uses base graphics, and the other [writeup] I found requires manual layout, and I have too many variables for that to be practical.

[lavaan]: http://lavaan.ugent.be/
[semPlot]: http://sachaepskamp.com/documentation/semPlot/semPaths.html 
[writeup]: https://www.ethan-young.com/posts/sem-diagrams-for-lavaan-models/

**Comment by malcolmbarrett** [comment]
Hey Neal! Fancy seeing you here. 

Unfortunately, ggdag does not currently support lavaan. I've thought about it, as I use lavaan a good deal myself. However, I'm still not sure it's quite in scope with this project, which is focused on causal diagrams. 

You're not out of options, though. You can use semPlot to create graph data, then convert it to a tidygraph for use with ggraph, upon which ggdag is based. Here's a somewhat bare example:

``` r
library(lavaan)
library(semPlot)
library(tidygraph)
library(ggraph)

HS.model <- ' visual  =~ x1 + x2 + x3 
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '
fit <- cfa(HS.model, data = HolzingerSwineford1939)

cfa_plot <- semPaths(fit, what = "Std", DoNotPlot = TRUE)

cfa_plot %>% 
  as_tbl_graph() %>% 
  ggraph() +
  geom_node_text(aes(label = label)) + 
  geom_edge_link(
    aes(
      start_cap = circle(5, "mm"), 
      end_cap = circle(5, "mm"),
      label = round(weight, 2)
    ),
    angle_calc = "along",
    label_dodge = unit(3, "mm"),
    arrow = grid::arrow(length = grid::unit(.2, "cm"), type = "closed")
  ) +
  theme_void()
```

![](https://i.imgur.com/F1D17FV.png)

<sup>Created on 2019-10-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by nfultz** [comment]
I found the magic incantation, maybe you will find it useful someday:

    HS.model %>% lavaan::lavaanify() %>% daggity::lavaanToGraph() %>% ggdag


![image](https://user-images.githubusercontent.com/418638/67330633-80ef0100-f4d1-11e9-86d0-4722075f7a38.png)
