### ISSUE TITLE
Posted linetype issue on cran repo

### ISSUE THREAD

**Issue by floswald** [malcolmbarrett/ggdag#18]
Hey

By mistake posted my issue on the cran mirror of this

https://github.com/cran/ggdag/issues/1#issue-527540182

Thanks

**Comment by malcolmbarrett** [comment]
Yes, definitely possible. What's a little different is that these geoms are based on ggraph edge geoms, which use `edge_linetype`:

``` r
confounder_triangle() %>% 
  tidy_dagitty() %>% 
  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) + 
    geom_dag_point() + 
    geom_dag_text() + 
    geom_dag_edges(edge_linetype = "dashed")
```

![](https://i.imgur.com/mRgHEz4.png)

<sup>Created on 2019-11-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

`edge_linetype` can also be treated as a mapping in `aes()` if you need more complex output than this. Could you please close the issue in the CRAN mirror, as well?

**Comment by floswald** [comment]
Great! I actually had gotten that far; now can one add a solid arrow from x to y in that picture ? I wanted to map the linetype from to an additional column of the dataframe (like “ is not z”) but I couldn’t make it work. Any ideas for that? Thanks

**Comment by malcolmbarrett** [comment]
Sure, you're on the right track. There are several ways, actually. Here's one:

``` r
library(ggdag)
library(dplyr)
confounder_triangle(x_y_associated = TRUE) %>% 
  tidy_dagitty() %>% 
  mutate(linetype = ifelse(name == "z", "dashed", "solid")) %>% 
  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) + 
  geom_dag_point() + 
  geom_dag_text() + 
  geom_dag_edges(aes(edge_linetype = linetype), show.legend = FALSE)
```

![](https://i.imgur.com/0SKrOlj.png)

<sup>Created on 2019-11-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by floswald** [comment]
Awesome. That’s *exactly* what I wanted to do (but must have messed up
somewhere).

Thanks so much!!
