### ISSUE TITLE
isFALSE deprecated?

### ISSUE THREAD

**Issue by achambaz** [malcolmbarrett/ggdag#2]
Hi, Thanks for the package. It seems that the dev version uses 'isFALSE', and that this function is now deprecated. Defining 
     isFALSE <- function(x) {is.logical(x) && length(x) == 1 && !is.na(x) && !x }
seems to solve the issue, at least temporarily.

**Comment by malcolmbarrett** [comment]
Can you provide a reproducible example of when you get a message about `isFALSE()` being deprecated? To my knowledge, it is not.

**Comment by achambaz** [comment]
At least, `isFALSE` does not seem to be defined in my version of `R` (3.4.4).

**Comment by malcolmbarrett** [comment]
Oh, apparently `isFALSE()` is new to R 3.5.0. That's not nearly a good enough reason to require R 3.5, so I'll define it for now. Thanks!
