### ISSUE TITLE
White nodes/points with black circle?

### ISSUE THREAD

**Issue by lebebr01** [malcolmbarrett/ggdag#22]
I've been playing with the package some and have a question about the behavior of the `geom_dag_point()` function. Ultimately, I'd like to be able to create a white filled in circle with a black circle around the node. 

Below I've shown what I've tried and it is not clear to me how the fill and color arguments differ. It also seems the behavior is different from ggplot2 where fill controls the fill of the point and the color controls the color of the circle around the point. 

Is this behavior possible within ggdag?

```r
g <- dagify(m ~ x + y, y ~ x)
p <- g %>%
  tidy_dagitty() %>%
  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_dag_edges() +
  theme_dag()
# Black nodes with white text
p +
  geom_dag_point() +
  geom_dag_text()

# White nodes, no circle, black text
p +
  geom_dag_node(color = 'white', fill = 'black') +
  geom_dag_text(color = 'black')

# Black nodes, black text
p +
  geom_dag_point(fill = 'white', color = 'black') +
  geom_dag_text(color = 'black')
```

**Comment by malcolmbarrett** [comment]
Hi there! Unless I misunderstand your post, you are actually mistaken about the default behavior of `geom_point()` in ggplot2. The default shape does *not* use a fill aesthetic, only color. To use the aesthetics as you describe, you need to change the shape, e.g. `shape = 21`. ggdag follows this behavior:

``` r
library(ggdag)
g <- dagify(m ~ x + y, y ~ x)
p <- g %>%
  tidy_dagitty() %>%
  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_dag_edges() +
  theme_dag()

p + 
  geom_point(fill = 'white', color = 'black')
```

![](https://i.imgur.com/FcXi1Er.png)

``` r

p + 
  geom_point(fill = 'white', color = 'black', shape = 21)
```

![](https://i.imgur.com/wovebhV.png)

``` r

p +
  geom_dag_point(fill = 'white', color = 'black', shape = 21) +
  geom_dag_text(color = 'black')
```

![](https://i.imgur.com/xYOTM6w.png)

<sup>Created on 2020-01-07 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by lebebr01** [comment]
Thank you! That was the missing piece in my understanding, the dreaded no fill parameter for default R shape. 👍 

Cheers!
