### ISSUE TITLE
Error with development version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [malcolmbarrett/ggdag#23]
The new version of ggplot2 has an updated `use_defaults()` method in `Geom`. As you overwrite this method it result in an error.

The new implementation is a bit more involved, so rather than completely overwriting it I'd suggest calling the parent method using `ggproto_parent()` and then do any additional modification you need

**Comment by malcolmbarrett** [comment]
Thank you! Do you have a sense of when the next ggplot2 release will be?

**Comment by thomasp85** [comment]
Around 24th of February

**Comment by malcolmbarrett** [comment]
Thanks, I'll get it resolved prior to then!
