### ISSUE TITLE
ggdag doesn't work when ggtext is loaded

### ISSUE THREAD

**Issue by njsilbiger** [malcolmbarrett/ggdag#37]
Hello,
I have been trying to implement titles in my DAGS that use ggtext, but it seems there is a conflict because ggtext is dependent on the github version of ggplot (which then doesn't allow me to make a ggdag plot). 

Thank you!

**Comment by malcolmbarrett** [comment]
Hi, thanks for your interest. ggdag 0.2.2 (new to CRAN) should work with the dev version of ggplot2. If that doesn't solve your issue, please feel free to re-open the issue. Let me know if you make anything nice looking with that combo of tools 😁
