### ISSUE TITLE
Labels failing for ggdag_equivalent_dags()

### ISSUE THREAD

**Issue by dgrisafe** [malcolmbarrett/ggdag#39]
Reprex:

# Simple dag model for confounding
dag_model <- dagify(
  y ~ x,
  y ~ z,
  x ~ z,
  labels = c("y" = "Outcome",
            "x" = "Exposure",
            "z" = "Confounder"),
  exposure = "x",
  outcome = "y") %>% 
  tidy_dagitty()

# Assess single possible confounding scenario
## labels work fine here
ggdag(.tdy_dag = dag_model, text = TRUE, use_labels = "label") + theme_dag()

# Equivalent dags for all possible confounding
## works fine without labels
ggdag_equivalent_dags(.tdy_dag = dag_model, text = TRUE) + theme_dag() 

# Add labels to equivalent dags
## will not run
ggdag_equivalent_dags(.tdy_dag = dag_model, text = TRUE, use_labels = "label") + theme_dag()

**Comment by malcolmbarrett** [comment]
Thanks! This looks like an issue with `node_equivalent_dags()`, which is not adding in additional data such as labels after tidying the equivalent DAGs
