### ISSUE TITLE
Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.

### ISSUE THREAD

**Issue by giacomovagni** [malcolmbarrett/ggdag#4]
When running `dagify(y ~~ x) %>% ggdag()` 
I get the following error 
`Error in mutate_impl(.data, dots) : 
  Evaluation error: `as_dictionary()` is defunct as of rlang 0.3.0.
Please use `as_data_pronoun()` instead.`

Any clue?
Thanks

**Comment by malcolmbarrett** [comment]
I can't replicate this issue. It looks like you have the dev version of rlang; maybe try reinstalling it? I don't explicitly use rlang in this package (although the tidyverse at large is quite dependent on it), so that's my best guess. I also tried this under the dev version of dplyr, but everything is running fine for me.

**Comment by giacomovagni** [comment]
OK thank you. I have tried to re-install rlang. 
Maybe it's my R version. Thanks.

**Comment by malcolmbarrett** [comment]
Actually, re-reading the error, it sort of looks like dplyr and rlang are out of sync. Maybe you should reinstall the dev version of dplyr?

**Comment by giacomovagni** [comment]
I had to re-install R actually. It's working now. Cool package by the way. 
Would be nice to have a special category for unobserved confounders.

**Comment by malcolmbarrett** [comment]
Huh! Well, glad you got it fixed and that you like the package.

For unmeasured variables, classify them as latent. This will correctly identify any bias but knows you can't control for that one, e.g.

``` r
dagify(
  y ~ x + z, x ~ z, 
  outcome = "y", 
  exposure = "x", 
  latent = "z"
) %>% 
  ggdag_adjustment_set()

#> Warning in dag_adjustment_sets(., exposure = exposure, outcome = outcome, : Failed to close backdoor paths. Common reasons include:
#>             * graph is not acyclic
#>             * backdoor paths are not closeable with given set of variables
#>             * necessary variables are unmeasured (latent)
```
![](https://i.imgur.com/ATIqQw8.png)
