### ISSUE TITLE
ggdag_equivalent_dags color

### ISSUE THREAD

**Issue by ASKurz** [malcolmbarrett/ggdag#41]
Hey @malcolmbarrett, 

I really like this package. Is there a way to directly control the color of the points and edges for `ggdag_equivalent_dags()`? At the moment, it appears to only color parametes are `text_col` and `label_col`.

**Comment by malcolmbarrett** [comment]
Thanks, @ASKurz! I've liked your work on the Bayes books quite a bit, myself!

Yes, that's true: I have intentionally avoided adding too many arguments to the quick plot functions. My philosophy here is that if you need to customize beyond the basics, you should use the underlying geom functions, as the quick plot functions are generally thin wrappers for that. That said, I think there's an argument that node and edge color are basic enough to be supported, and I may go in that direction in the next release. Anyway, here's how I would write it in the geom form:

``` r
library(ggdag)
g_ex <- dagify(y ~ x + z, x ~ z)

g_ex %>% 
  node_equivalent_dags() %>% 
  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) + 
  geom_dag_point(color = "steelblue") + 
  geom_dag_text() + 
  geom_dag_edges(edge_color = "steelblue") +
  facet_wrap(~dag) +
  theme_dag() +
  expand_plot(
    expand_x = expansion(c(0.25, 0.25)),
    expand_y = expansion(c(0.25, 0.25))
  )
```

![](https://i.imgur.com/2KNmN4M.png)

<sup>Created on 2020-05-27 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by ASKurz** [comment]
This is helpful. Thanks and thanks for the kind words. I’m in the early stages of working through McElreath’s second edition and it looks like **ggdag** will play a big role.

**Comment by malcolmbarrett** [comment]
That's great! I was aware he was using DAGs for this one (I have an order in to get it later in the year 😄)

**Comment by ASKurz** [comment]
Loosely related follow-up: I see that, in the example you gave above, the plot is faceted by `dag`. If I’m specifying multiple DAGs from the ground up, what’s the preferred way to combine them. E.g., 

```
d1 <- 
  dagify(X ~ Z,
         Y ~ Z,
         coords = tibble(dag = "The Fork",
                         name = c("X", "Y", "Z"),
                         x = c(1, 3, 2),
                         y = c(2, 1, 2)))

d2 <- 
  dagify(Z ~ X,
         Y ~ Z,
         coords = tibble(dag = "The Pipe",
                         name = c("X", "Y", "Z"),
                         x = c(1, 3, 2),
                         y = c(2, 1, 1.5)))
```

How does one combine `d1` and `d2` into a single object which might be later faceted with `facet_wrap(~dag)`?

**Comment by malcolmbarrett** [comment]
Hm there's not a true way to have multiple DAGs. In general, each `tidy_dagitty()` object has one `daggity` object associated with it, but I'm definitely not against a better setup that would let you bind or merge DAGs.

Here are a couple of hacks, though. This one uses the basic setup you have:

``` r
library(ggdag)
library(dplyr)

d1 <- 
  dagify(X ~ Z,
         Y ~ Z,
         coords = tibble(dag = "The Fork",
                         name = c("X", "Y", "Z"),
                         x = c(1, 3, 2),
                         y = c(2, 1, 2))) %>% 
  tidy_dagitty()

d2 <- 
  dagify(Z ~ X,
         Y ~ Z,
         coords = tibble(dag = "The Pipe",
                         name = c("X", "Y", "Z"),
                         x = c(1, 3, 2),
                         y = c(2, 1, 1.5))) %>% 
  tidy_dagitty()

d1$data <- dplyr::bind_rows(d1$data, d2$data, .id = "dag")


ggdag(d1) + facet_wrap(~dag)
```

![](https://i.imgur.com/hbTJaTs.png)

Here's another way using a single DAG (but you'd have to hack together a facetting variable):

``` r
d3 <- 
  dagify(
    # DAG 1
    X1 ~ Z1,
    Y1 ~ Z1,
    # DAG 2
    Z2 ~ X2,
    Y2 ~ Z2
    # You can also label these to make them appear the same
  ) %>% 
  tidy_dagitty()

ggdag(d3)
```

![](https://i.imgur.com/EDKb20w.png)

<sup>Created on 2020-05-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by malcolmbarrett** [comment]
Oh, I should warn you that the first example may not work forever as the internal structure may change in a future release such that the data is stored in some other way than `dag$data`, although the general idea will continue to work.

**Comment by ASKurz** [comment]
Got it. Hey thanks for working through a couple solutions. If you ever come up with a general and stable solution, I would be most interested. In the meantime, it looks like your first solution will get me moving.

**Comment by ASKurz** [comment]
In case anyone else is interested, this also works:

```
library(tidyverse)
library(ggdag)
d1 <- 
  dagify(X ~ Z,
         Y ~ Z,
         coords = tibble(name = c("X", "Y", "Z"),
                         x = c(1, 3, 2),
                         y = c(2, 1, 2)))

d2 <- 
  dagify(Z ~ X,
         Y ~ Z,
         coords = tibble(name = c("X", "Y", "Z"),
                         x = c(1, 3, 2),
                         y = c(2, 1, 1.5)))

p1 <- gg_simple_dag(d1) + ggtitle("The Fork")
p2 <- gg_simple_dag(d2) + ggtitle("The Pipe")

library(patchwork)
p1 + p2
```

**Comment by nbreznau** [comment]
We are developing a package that uses ggdag plotting and wonder if there is any way to change the color of unique edges? So different edge colors in the same DAG. The ggplot2 function of geom_dag_edges() changes this for all edges. Thanks for this awesome package.

**Comment by malcolmbarrett** [comment]
@nbreznau `edge_color` is an aesthetic, so `aes(edge_color = column_with_uniqe_edges)` is the trick. You might need to use `geom_dag_edges_link()` or another more specific edge function, depending on your needs. Please follow up on a new issue if you have more questions.
