### ISSUE TITLE
could not find function "ggproto"

### ISSUE THREAD

**Issue by BS1125** [malcolmbarrett/ggdag#45]
Hi, I got an error when I was running this code:

> ggdag::ggdag(ggdag::dagify(A ~ B, A ~ C, B ~ C))
Error in ggproto(NULL, self, scales = lapply(self$scales, function(s) s$clone())) : 
  could not find function "ggproto"

I know this can be solved by loading ggplot2, but is there a way of getting rid of this error without loading ggplot2?

Thank you

**Comment by malcolmbarrett** [comment]
Can you tell me a little more about the context in which you're using the code like this? Is this in a package, perhaps? 

Basically, you have two other options. If you're not using this in a package, something like this might help:

``` r
ggproto <- ggplot2::ggproto
ggdag::ggdag(ggdag::dagify(A ~ B, A ~ C, B ~ C))
```

If you're in a package, consider:

``` r
#' @importFrom ggplot2 ggproto
ggdag::ggdag(ggdag::dagify(A ~ B, A ~ C, B ~ C))
```

The root issue here is the way ggdag [depends](https://github.com/malcolmbarrett/ggdag/blob/12e43e46b753326b8b5d9a6ac5748ce5145b5651/DESCRIPTION#L20-L21) on ggplot2; it expects that you're using it with ggplot2 and that it's loaded, an approach sometimes used in ggplot extensions. I have already been wondering if I can change this to deal with it in a different way. 

If I've answered your question adequately, please close this issue, as I file a different issue for the root problem.

**Comment by BS1125** [comment]
Thank you so much! I’m using it in a package. I tried using importFrom but I still get the same error. Let me figure out why myself.

**Comment by BS1125** [comment]
Thank you so much! I’m using it in a package. I tried using importFrom but I still get the same error. Let me figure out why myself.

**Comment by BS1125** [comment]
Thank you so much! I’m using it in a package. I tried using importFrom but I still get the same error. Let me figure out why myself.

**Comment by BS1125** [comment]
Thank you so much! I’m using it in a package. I tried using importFrom but I still get the same error. Let me figure out why myself.

**Comment by BS1125** [comment]
Thank you so much! I’m using it in a package. I tried using importFrom but I still get the same error. Let me figure out why myself.

**Comment by BS1125** [comment]
Thank you so much! I’m using it in a package. I tried using importFrom but I still get the same error. Let me figure out why myself.

**Comment by malcolmbarrett** [comment]
Putting `ggproto <- ggplot2::ggproto` (without exporting) may also work for you in the case of a package. Let me know how it goes

**Comment by BS1125** [comment]
Thank you so much! I’m using it in a package. I tried using importFrom but I still get the same error. Let me figure out why myself.

**Comment by nfultz** [comment]
Can you reopen this issue? It looks exactly like what we encountered at https://github.com/ben-oneill/utilities/pull/3

Our workaround was a little different, we used `fortify()` and configured the scales directly.

Thanks again.

**Comment by malcolmbarrett** [comment]
In that case, it will in theory be dealt with when I deal with #46. Thanks for filing

**Comment by malcolmbarrett** [comment]
FYI this is fixed in the dev version, which I will ship to CRAN soon
