### ISSUE TITLE
Docker Install Unable to Load Shared Object

### ISSUE THREAD

**Issue by GrayAlex49** [malcolmbarrett/ggdag#47]
I'm trying to add ggdag to the rocker/shiny-verse docker image. When installing from source you get 

```
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/local/lib/R/site-library/igraph/libs/igraph.so':
  libglpk.so.40: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
```
If using install2.r (from CRAN) it installs but then fails to load

```
app_1  | Error: package or namespace load failed for ‘ggdag’ in dyn.load(file, DLLpath = DLLpath, ...):
app_1  |  unable to load shared object '/usr/local/lib/R/site-library/igraph/libs/igraph.so':
app_1  |   libglpk.so.40: cannot open shared object file: No such file or directory
app_1  | Execution halted
```

Dockerfile:
```
FROM rocker/shiny-verse
RUN install2.r ggdag
```
I've tried installing igraph in a bunch of different ways as well that hasn't resolved the issue.

**Comment by malcolmbarrett** [comment]
Unfortunately, I don't know much about Docker. To my eye, this looks like an igraph issue. Are your attempts to install igraph successful, or do you get the same sort of message?

**Comment by GrayAlex49** [comment]
igraphs seems to be installing without a problem (from CRAN at least, remotes cant find it on github for some reason). I can see if I can come up with a test of just igraphs in docker.

**Comment by malcolmbarrett** [comment]
ggdag isn't doing anything unusual with igraph, so I have a hard time imagining that that is a problem. I don't see ggraph in your error but that package does the heavy lifting with igraph, so it's possible the root issue is related to that package. This sure seems like an issue with compiling igraph, though!

**Comment by malcolmbarrett** [comment]
PS this seems like a similar issue, and the person had a broken version of igraph installed that needed to be removed: https://github.com/bwlewis/rthreejs/issues/83

**Comment by GrayAlex49** [comment]
Yeah I just recreated the issue using only igraph. Thanks for checking it out, sorry for the inconvenience. 

https://github.com/igraph/rigraph/issues/418
