### ISSUE TITLE
Error: Problem with `summarise()` input `..1`.

### ISSUE THREAD

**Issue by benrosche** [malcolmbarrett/ggdag#48]
The DAG below produces the following error:

> <error/dplyr_error>
Problem with `summarise()` input `..1`.
x Problem with `filter()` input `..1`.
x Input `..1` must be of size 34 or 1, not size 55.
i Input `..1` is `name == df[["Var1"]]`.
i Input `..1` is `{ ... }`.

and the following warnings: 

> In name == df[["Var1"]] :  longer object length is not a multiple of shorter object length

when calling:

> ggdag_dseparated(dag, from="Yj1", to="Yi2", controlling_for = c("Yi1", "Yj1", "Aij1", "Aij2", "SESi", "SESj"))

DAG:

> coords <- tibble::tribble(
  ~name, ~x,  ~y,
  "SESi", 1.5,   3,
  "Ii",   1.5, 2.2,
  "SIi",  2.25,  2.9,
  "Si",   2.25,  2,
  "Yi1",  2,   2,
  "Yi2",  2,   1,
  "SESj", 3.5,   3,
  "Ij",   3.5, 2.2,
  "Sj",   2.75,  2,
  "SIj",  2.75,  2.9,
  "Yj1",  3,   2,
  "Yj2",  3,   1,
  "Aij1", 2.5, 2.5,
  "Aij2", 2.5, 1.5
)
dag <- dagify(
  Yi1 ~ SESi + Aij1 + Ii + SIi,
  Yi2 ~ SESi + Aij2 + Yi1 + Yj1 + Ii + SIi,
  Yj1 ~ SESj + Aij1 + Ij + SIj,
  Yj2 ~ SESj + Aij2 + Ij + SIj,
  Aij1 ~ SESi + SESj + SIi + SIj + Si + Sj,
  Aij2 ~ SESi + SESj + SIi + SIj + Si + Sj + Yi1 + Yj1,
  coords = coords
  ) 
dag %>% ggdag(edge_type = "diagonal")

**Comment by malcolmbarrett** [comment]
Thanks for filing. Unfortunately, I am not able to replicate this error. Could you please update your packages, especially dplyr and ggdag, to their latest versions? Also, if the issue continues, try installing the development versions of each. If updating your packages doesn't resolve the issue, please share the results of `sessionInfo()` here

**Comment by benrosche** [comment]
Thank you for your reply. 

I have installed the development version of dplyr and ggdag now and also updated all other packages. Here is my sessionInfo()

> R version 4.0.2 (2020-06-22)
> Platform: x86_64-w64-mingw32/x64 (64-bit)
> Running under: Windows 10 x64 (build 19041)
> 
> Matrix products: default
> 
> locale:
> [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
> [5] LC_TIME=English_United States.1252    
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
>  [1] ggdag_0.2.2.9000 dagitty_0.3-0    forcats_0.5.0    stringr_1.4.0    dplyr_1.0.2.9000 purrr_0.3.4      readr_1.4.0      tidyr_1.1.2      tibble_3.0.3    
> [10] ggplot2_3.3.2    tidyverse_1.3.0 
> 
> loaded via a namespace (and not attached):
>  [1] tidyselect_1.1.0   graphlayouts_0.7.0 haven_2.3.1        V8_3.2.0           colorspace_1.4-1   vctrs_0.3.4        generics_0.0.2     viridisLite_0.3.0 
>  [9] blob_1.2.1         rlang_0.4.7        pillar_1.4.6       glue_1.4.2         withr_2.3.0        DBI_1.1.0          tweenr_1.0.1       dbplyr_1.4.4      
> [17] modelr_0.1.8       readxl_1.3.1       lifecycle_0.2.0    munsell_0.5.0      gtable_0.3.0       cellranger_1.1.0   rvest_0.3.6        curl_4.3          
> [25] fansi_0.4.1        tidygraph_1.2.0    broom_0.7.1        Rcpp_1.0.5         scales_1.1.1       backports_1.1.10   jsonlite_1.7.1     farver_2.0.3      
> [33] fs_1.5.0           gridExtra_2.3      ggforce_0.3.2      hms_0.5.3          digest_0.6.25      stringi_1.5.3      ggrepel_0.8.2      polyclip_1.10-0   
> [41] grid_4.0.2         cli_2.0.2          tools_4.0.2        magrittr_1.5       ggraph_2.0.3       crayon_1.3.4       pkgconfig_2.0.3    ellipsis_0.3.1    
> [49] MASS_7.3-51.6      xml2_1.3.2         reprex_0.3.0       lubridate_1.7.9    viridis_0.5.1      assertthat_0.2.1   httr_1.4.2         rstudioapi_0.11   
> [57] R6_2.4.1           boot_1.3-25        igraph_1.2.5       compiler_4.0.2    

I still get the error, unfortunately.

**Comment by malcolmbarrett** [comment]
Oh, sorry, I misunderstood your code. I mistakenly assumed you meant the last line produced an error. I am able to replicate this, after all.

This is actually an issue with `activate_collider_paths()` caused by the high number of paths activated by controlling for a collider in this example. Here's a simpler reprex:

``` r
library(ggdag)
dagify(
  m ~ a + b + d + e + f + g,
  x ~ a,
  y ~ b + x,
  exposure = "x",
  outcome = "y"
) %>% activate_collider_paths(adjust_for = c("m"))
#> Warning in name == df[["Var1"]]: longer object length is not a multiple of
#> shorter object length
#> Error: Problem with `summarise()` input `..1`.
#> x Problem with `filter()` input `..1`.
#> x Input `..1` must be of size 11 or 1, not size 15.
#> ℹ Input `..1` is `name == df[["Var1"]]`.
#> ℹ Input `..1` is `{ ... }`.
```

<sup>Created on 2020-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I'll have a patch up soon. Thanks again for filing.
