### ISSUE TITLE
straight and curved edges in the same plot

### ISSUE THREAD

**Issue by gbiele** [malcolmbarrett/ggdag#5]
Thanks for working on this package!

Is there a simple way to have straight and curved (arced) edges in the same DAG?
I am thinking of something along the lines of `arrow_directed`, for example `edge_straight` and `edge_arced`.

It might be possible to hack a solution by using `geom_dag_edges` and `geom_dag_edges_arc`  and to specify which edges should be plotted with each command. But a simple flag like `edge_straight` would make life much easier.

 Currently I get the following error message when I try to specify only a subset of the data for the straight edges: 

```
Error in geom_dag_edges(curvature = 0, data = tselDAG$data[tselDAG$data$name ==  : 
  argument 2 matches multiple formal arguments
```
So it looks as if geom_dag_edges doesn't accept when I specify different data than in the orgional ggplot call.

Here is the full example:

```
selDAG = dagitty("dag {
S [pos=\"0,-1\"]
                 X [pos=\"1,0\"]
                 Y [pos=\"-.65,0\"]
                 L [pos=\"0,1\"]
                 L -> X
                 L -> S [pos=\"-1.6,0\"]
                 Y -> S
                 }")


tselDAG = tidy_dagitty(selDAG)


g = ggplot(tselDAG,
           aes(x = x, y = y, xend = xend, yend = yend)) + 
  geom_dag_edges(curvature = 0,
                 data = tselDAG$data[tselDAG$data$name == "L" & tselDAG$data$to == "S",]) +
  geom_dag_edges_arc(curvature = -1,
                     data = tselDAG$data[tselDAG$data$name == "L" & tselDAG$data$to == "S",]) +
  geom_dag_text(col = "black")
```

**Comment by malcolmbarrett** [comment]
So, I think I will have an answer for you regardless, but I'm a little unclear about the end result you want. Could you please clarify? The code you post makes it seem like you want only two arrows, one straight and one curved, both going from `L` to `S`. Is that right? Or did you just want `L` to `S` curved with `L` -> `X` and `Y` -> `S` straight?

**Comment by gbiele** [comment]
Sorry for being unclear.

The solution below works, but a shorter solution would be appreciated.

```
library(dagitty)
library(ggdag)
library(data.table)

selDAG = dagitty("dag {
S [pos=\"0,-1\"]
                 X [pos=\"-.65,0\"]
                 Y [pos=\".65,0\"]
                 L [pos=\"0,1\"]
                 L -> Y
                 L -> S 
                 X -> S
                 }")

exposures(selDAG) = "X"
outcomes(selDAG) = "Y"
adjustedNodes(selDAG) = "S"

dtselDAG = data.table(tidy_dagitty(selDAG)$data)
dtselDAG[, conditioned_on := "No"]
dtselDAG[name == "S", conditioned_on := "Yes"]

g = ggplot(dtselDAG[!(name == "L" & to == "S"),],
           aes(x = x, y = y, xend = xend, yend = yend)) + 
  theme_dag() +
  theme(panel.background = element_rect(fill = "white"), 
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()) +
  geom_dag_point(col = "white", show.legend = F) +
  geom_dag_text(col = "black") +
  geom_dag_edges() +
  geom_point(data = dtselDAG[name == "S",],
             pch = 0,
             size = 10) +
  geom_dag_edges_arc(curvature = -1,
                     data = dtselDAG[name == "L" & to == "S",])

g
```

**Comment by malcolmbarrett** [comment]
Ok, I thought so. You have several additional options. The tricky thing is that you (very reasonably) are treating the arc as an aesthetic, but in fact, it is a geom. I've thought about this a bit myself, but that's how it is in the underlying ggraph package. I have been thinking about proposing a change to `ggraph` that will more easily allow that, but I'm not totally convinced it's the right move yet. (Sorry I had to switch to dplyr; I don't know data.table well enough to suggest code for it.)

Nevertheless, there are a few ways to go about it

1. Use `geom_dag_edges_link()` and `geom_dag_edges_arc()` to make straight and curved lines
2. Use `geom_dag_edges()`, which is essentially a wrapper for the above, to do so. Note that it assumes curved lines are bidirected, so you have to tell it not to add arrows to both sides.
3. Use `geom_dag_edges_arc()` alone and give a vector of curves. This is probably more in the spirit of what you're after.

``` r
library(dagitty)
library(ggdag)
library(dplyr)

selDAG <- dagitty("dag {
                 S [pos=\"0,-1\"]
                 X [pos=\"-.65,0\"]
                 Y [pos=\".65,0\"]
                 L [pos=\"0,1\"]
                 L -> Y
                 L -> S 
                 X -> S
                 }")

exposures(selDAG) <- "X"
outcomes(selDAG) <- "Y"
adjustedNodes(selDAG) <- "S"

g <- selDAG %>% 
  tidy_dagitty() %>%
  ggplot(aes(x = x, y = y, xend = xend, yend = yend)) +
  geom_dag_text(col = "black") +
  geom_point(
    data = function(x) filter(x, name == "S"),
    pch = 0,
    size = 10
  ) +
  theme_dag() +
  theme(
    panel.background = element_rect(fill = "white"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank()
  )

######## option one ######## 

g + 
  geom_dag_edges_link(
    data = function(x) filter(x, !(name == "L" & to == "S"))
  ) +
  geom_dag_edges_arc(
    data = function(x) filter(x, name == "L" & to == "S"),
    curvature = -1
  ) 
```

![](https://i.imgur.com/JABwsjV.png)

``` r

######## option two ######## 

g + 
  geom_dag_edges(
    data_directed = function(x) filter(x, !(name == "L" & to == "S")),
    data_bidirected = function(x) filter(x, name == "L" & to == "S"),
    arrow_bidirected = grid::arrow(length = grid::unit(5, "pt"), type = "closed"),
    curvature = -1
  ) 
```

![](https://i.imgur.com/Vc1C2zo.png)

``` r

######## option three ######## 

g + 
  geom_dag_edges_arc(
    curvature = c(-1, 0, 0)
  )
```

![](https://i.imgur.com/Ox10rc0.png)

**Comment by malcolmbarrett** [comment]
I'm going to close this. Please feel free to reopen if this doesn't address your concern.
