### ISSUE TITLE
Adding labels to edges (weights)

### ISSUE THREAD

**Issue by Phlogi** [malcolmbarrett/ggdag#50]
Is there a way to label the edges manually or to add information about the weight of an edge? Please see the example below:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/6451003/103556375-fb772700-4eb1-11eb-94de-531243e59049.png">

**Comment by malcolmbarrett** [comment]
Can you please clarify your question? It looks from your example like you've already figured out how to annotate edges. FWIW, you can use the techniques discussed here: https://www.data-imaginist.com/2017/ggraph-introduction-edges#labels. ggdag is based on ggraph, so ggdag's geoms will accept those types of arguments

**Comment by Phlogi** [comment]
Well I did use a PDF editor (Preview) for that. Thanks for the link, I figured it out, here is a minimal example if anyone ever comes here:

```
dag <- dagify(Y ~ X + H,
              X ~ A + H,
              exposure = "X",
              outcome = "Y")
t_dag <- tidy_dagitty(dag)
t_dag$data$edge <- c('1','2','3','4','')

t_dag %>%
ggplot(aes(x = x, y = y, xend = xend, yend = yend, label=edge)) +
  geom_dag_point() +
  geom_dag_edges() +
  geom_dag_text() +
  theme_dag()
```

PS: Just need to format and repel that better.
