### ISSUE TITLE
ggdag functionality to plot nodes without edges

### ISSUE THREAD

**Issue by anhthyngo** [malcolmbarrett/ggdag#64]
I am currently using ggdag (it’s awesome) to display causal discovery outputs.

 

I plot the following DAG which results from the PC algorithm given my dataset.

 

```
Dag <- dagitty::dagitty('dag {
age
age_cat
age_factor
c_charge_degree
crime_factor
days_b_screening_arrest
decile_score
gender_factor
is_recid
length_of_stay
priors_count
race
race_factor
score_factor
score_text
sex
two_year_recid
decile_score <-> is_recid
is_recid <-> two_year_recid
}')
```

When I call `ggdag::ggdag(Dag)` I only get the following graph, which only displays the nodes with edges. How can I use ggdag to display all nodes?  i.e. the nodes without edges will appear as isolated nodes.
 
![image](https://user-images.githubusercontent.com/24724780/142227791-601d2644-b805-4429-96dc-de2d141192fd.png)

**Comment by malcolmbarrett** [comment]
Fixed in #68, thanks!

``` r
Dag <- dagitty::dagitty('dag {
age
age_cat
age_factor
c_charge_degree
crime_factor
days_b_screening_arrest
decile_score
gender_factor
is_recid
length_of_stay
priors_count
race
race_factor
score_factor
score_text
sex
two_year_recid
decile_score <-> is_recid
is_recid <-> two_year_recid
}')
ggdag::ggdag(Dag)
```

![](https://i.imgur.com/jAUCTvh.png)

<sup>Created on 2022-04-14 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
