### ISSUE TITLE
ggdag theme breaks ggplot2 displays

### ISSUE THREAD

**Issue by sjgenco** [malcolmbarrett/ggdag#67]
## Description

Here is a simple ggplot barplot definition:
```# Load ggplot2
library(ggplot2)

# Create data
data <- data.frame(
  name=c("A","B","C","D","E") ,  
  value=c(3,12,5,18,45),
  group=c("Group1", "Group1", "Group1", "Group2", "Group2")
  )

# Barplot
ggplot(data, aes(x=name, y=value, fill=group)) + 
  geom_bar(stat = "identity") +
  labs(x="X axis label", y="y axis label") +
  scale_fill_discrete(name = "Legend", 
       labels = c("Group1", "Group2")) +
  ggtitle("This is the title") +
  theme(axis.text.x = element_text())
```
I noticed when I ran this code in a cell in Jupyterlab, it produced an incorrect display of the plot, leaving out the x & y axis labels and the y-axis tick labels. After initially assuming this was a Jupyterlab problem, I discovered that it was actually a result of the `ggdag` customized `set theme` command I had set earlier in the notebook:

```ggplot2::theme_set(theme_dag_grey_grid(base_size = 18))```

When I replaced this command with the original ggplot2 theme
```ggplot2::theme_set(theme_grey(base_size = 18))```
all the graphs later in the notebook rendered correctly.

## Reproduce

Here's the correct graph as produced in RStudio:
<img width="757" alt="image" src="https://user-images.githubusercontent.com/19754884/162590009-33716ade-0ae6-4bdd-9980-6c585a024a35.png">

And here's the result in Jupyterlab after calling `ggplot2::theme_set(theme_dag_grey_grid(base_size = 18))`:
<img width="579" alt="image" src="https://user-images.githubusercontent.com/19754884/162633231-3e3d7dd1-8c80-4379-b75f-41e9783aad87.png">

When I replace the `ggdag` theme with the default `ggplot2` theme listed above, the missing labels reappear:
<img width="654" alt="image" src="https://user-images.githubusercontent.com/19754884/162633156-26f0fa99-d302-4804-aa21-7d6f9a87e514.png">

## Context

- Operating System and version: MacOS Monterey 12.2.1
- Browser and version: Chrome Version 100.0.4896.75 (Official Build) (x86_64)
- JupyterLab version: 3.3.3
-  Anaconda 2.1.4

**Comment by malcolmbarrett** [comment]
This is not a bug. Themes in ggdag disable axis text by default because that is usually what you want in a DAG. As you show in your example, you can easily add them back in as necessary with, e.g., `theme(axis.text.x = element_text())`
