### ISSUE TITLE
Text on top of the arrows

### ISSUE THREAD

**Issue by DM087** [malcolmbarrett/ggdag#72]
Hi,

Many thanks for this wonderful R package. Is it possible to have text on top of the arrows? Please see the attached image for an example (v>>z2). Many thanks.  
![ggdag-1](https://user-images.githubusercontent.com/75045432/181286936-a5b2ff7c-df85-4fef-a0aa-f80983d36dfd.png)

**Comment by DM087** [comment]
Seems like I can use `annotate`.

**Comment by malcolmbarrett** [comment]
You'll also want to check out this example from ggraph (the second to last one): https://www.data-imaginist.com/2017/ggraph-introduction-edges/. ggdag geoms support `label` and the `along` option for labeling

**Comment by DM087** [comment]
@malcolmbarrett many thanks.
