### ISSUE TITLE
Issues with next version of ggplot2

### ISSUE THREAD

**Issue by thomasp85** [malcolmbarrett/ggdag#76]
Hi

We preparing the next release of ggplot2 and our reverse dependency checks show that your package is failing with the new version. Looking into it we see that your package somehow includes references to ggplot2 code from when it was build, which causes the check to emit the "Import not declared from..." error. Please see https://www.tidyverse.org/blog/2022/09/playing-on-the-same-team-as-your-dependecy/ for some more info about why this can cause issues.

Note that we are also seeing additional issues related to our internal switch to vctrs, but we are still looking into if this can be alleviated in ggplot2 itself.

You can install the release candidate of ggplot2 using `devtools::install_github('tidyverse/ggplot2@v3.4.0-rc')` to test this out.

We plan to submit ggplot2 by the end of October and hope you can have a fix ready before then

Kind regards
Thomas

**Comment by malcolmbarrett** [comment]
I think I've identified the cause of the error you mention (a hack related to the switch to `expansion()` that I never updated), but I'm getting too many errors and warnings from that release candidate to confirm. 

I'm seeing a lot of things like 

```r
Error in `vec_size()`:
! `x` must be a vector, not an environment.
```

and 

```r
Warning messages:
1: In structure(in_domain, pos = match(in_domain, breaks)) :
  Calling 'structure(NULL, *)' is deprecated, as NULL cannot have attributes.
  Consider 'structure(list(), *)' instead.
```

Are these things stemming from the additional issues you're seeing, or should I investigate on my end?

**Comment by thomasp85** [comment]
Hi. The first is from using an old version of vctrs. If you install the latest version you should see it disappear. The last has been fixed in the latest rc so hopefully that is also clear if you update ggplot2
