### ISSUE TITLE
How to incorporate hovers?

### ISSUE THREAD

**Issue by nicholekulikowski** [malcolmbarrett/ggdag#80]
Thank you for the package! I love how easy it is to use.

My question is- do you know how I could possibly make this into a html object and add hovers? (i.e. like a plotly figure)? I need to do so for a static site, but am a little stuck. Thanks!

**Comment by malcolmbarrett** [comment]
To my knowledge, it's not yet possible to use plotly with ggraph (which is what ggdag uses as a backend) https://github.com/plotly/plotly.R/pull/1326

**Comment by malcolmbarrett** [comment]
Actually, using ggiraph looks promising: https://stackoverflow.com/questions/62659308/convert-ggraph-to-interative-plot-with-plotyly-or-network3d

**Comment by malcolmbarrett** [comment]
I think that's the answer, so I'm going to close this
