### ISSUE TITLE
Reducing white space between nodes

### ISSUE THREAD

**Issue by hail2thief** [malcolmbarrett/ggdag#81]
First: this is such an amazing resource for teaching and research, thank you. Second: I use `ggdag` a lot in my slides and wish there was an easy way (beyond manually setting coordinates) to reduce the white space between nodes. Are there any tips or tricks I might be missing?

**Comment by malcolmbarrett** [comment]
I'm not totally sure what you mean by reduce white space. Can you please elaborate?

**Comment by hail2thief** [comment]
Is there a way, for example, to determine how close the nodes are in this graph / or otherwise reduce the amount of "white space" in this plot? Thanks for your input! Might not have anything to do with `ggdag`.
<img width="1391" alt="Screenshot 2023-02-26 at 2 00 15 PM" src="https://user-images.githubusercontent.com/5944086/221440118-7cc9d5ab-54e3-449e-ac7d-6d4b465567c2.png">


code below: 

```
dagify(Support ~ Ad, 
       exposure = "Ad", 
       outcome = "Support") %>% 
  ggdag_status(text = FALSE, use_labels = "name") + theme_dag() + 
  theme(legend.position = "none")

**Comment by hail2thief** [comment]
Beautiful, thank you!
