### ISSUE TITLE
Time ordered DAGs

### ISSUE THREAD

**Issue by LucyMcGowan** [malcolmbarrett/ggdag#83]
I know we've talked about this a lot, but what do you think about making some simple helpers to make time ordering the DAG quite easy? I find myself always creating coordinates which is ok but a bit burdensome and also I almost always forget how and how to look up old code 😂 

Inspired today by: https://twitter.com/seanjtaylor/status/1602722830013153284?s=20&t=0HUmyZ0ifJVjIcvgdTaRRw

**Comment by malcolmbarrett** [comment]
Maybe something like `coords = time_ordered(list(`1` = list(c("c1, "c2"), `2` =  list("x"), `1` =  list("y"))`

**Comment by malcolmbarrett** [comment]
I also looked into applying layout algorithms in one dimension only (e.g. set x as fixed but apply algorithm to y) but didn't have much luck

Maybe tikz's above, below, etc API is a good inspiration, as well

**Comment by malcolmbarrett** [comment]
@LucyMcGowan what do you think of this API? The user provides a series of character vectors which are times 1:n by default. (Can specify time numbers manually as well)

``` r
library(ggdag)
coords <- time_ordered_coords(
  "a", 
  c("b", "c"), 
  "d", 
  c("e", "f", "g"),
  c("h", "i", "j", "k"),
  "l"
)

dagify(
  l ~ h + i + j + k,
  i ~ e + f + g,
  e ~ d,
  d ~ b + c,
  c ~ a,
  coords = coords
) |>
  ggdag()
```

![](https://i.imgur.com/d6zkLen.png)

<sup>Created on 2023-02-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by malcolmbarrett** [comment]
Accepting dataframes: 

``` r
library(ggdag)
x <- data.frame(
  name = c("x1", "x2", "y", "z1", "z2", "z3", "a"), 
  time = c(1, 1, 2, 3, 3, 3, 4)
)

dagify(
  z3 ~ y, 
  y ~ x1 + x2, 
  a ~ z1 + z2 + z3, 
  coords = time_ordered_coords(x)
) |> 
  ggdag()
```

![](https://i.imgur.com/FcVefAO.png)

<sup>Created on 2023-02-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by malcolmbarrett** [comment]
``` r
library(ggdag)
#> 
#> Attaching package: 'ggdag'
#> The following object is masked from 'package:stats':
#> 
#>     filter
x <- data.frame(
  name = c("x1", "x2", "y", "z1", "z2", "z3", "a"), 
  time = c(1, 1, 2, 3, 3, 3, 4)
)
dagify(
  z3 ~ y, 
  y ~ x1 + x2, 
  a ~ z1 + z2 + z3, 
  coords = time_ordered_coords(x)
) |> 
  ggdag()
```

![](https://i.imgur.com/FcVefAO.png)

<sup>Created on 2023-02-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by LucyMcGowan** [comment]
YES 🙌
